[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tping"
readme = "README.md"
version = "3.1.0"
description = "EchoRequest and EchoReply Module"
dependencies = "tchecksum"
