[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tping"
version = "3.1.0"
description = "EchoRequest and EchoReply Module"
requires-python = "==3.10.*"
dependencies = [
    "tchecksum~=1.21"
]
