[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tping"
version = "1.0.2"
description = "EchoRequest and EchoReply Module"
dependencies = [
    "tchecksum@git+https://github.com/tango3304/tchecksum.git@v1.0",
]
