[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tping"
version = "3.1.0"
description = "EchoRequest and EchoReply Module"
dependencies = ["https://github.com/tango3304/tchecksum.git"]
