[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tping"
version = "3.1.0"
description = "EchoRequest and EchoReply Module"
requires-python = "==3.10.*"
dependencies = [
    "tchecksum~=1.21"
]
